version: '3.8'

services:
  cyberai-bot-edge:
    build:
      context: ..
      dockerfile: docker/edge.Dockerfile
    container_name: cyberai-bot-edge
    ports:
      - "8000:8000"  # API server
      - "8080:8080"  # Dashboard
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
      - ../config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

networks:
  default:
    name: cyberai-edge-network